version: "3.9"
services:
  postgres:
    container_name: transport_company_postgres
    image: postgres:16.0
    restart: unless-stopped
    ports:
      - "2345:5432"
    environment:
      - POSTGRES_DB=transport_company
      - POSTGRES_PASSWORD=postgres
    volumes:
      - transport-company-postgresql-data:/var/lib/postgresql/data
volumes:
  transport-company-postgresql-data:
