version: "3.9"
services:
  postgres:
    container_name: carrier_company_postgres
    image: postgres:16.0
    restart: always
    ports:
      - "2345:5432"
    environment:
      - POSTGRES_DB=carrier_company
      - POSTGRES_PASSWORD=postgres
    volumes:
      - carrier-company-postgresql-data:/var/lib/postgresql/data
volumes:
  carrier-company-postgresql-data:
